version: '3'

services:
  pupy:
    image: alxchk/pupy:unstable
    user: pupy
    volumes:
      - .:/opt/pupy
    ports:
      - 8443:8443
    container_name: pupy
    stdin_open: true
    tty: true
