version: '3'

services:
  pupy:
    image: alxchk/pupy:base-${TAG}
    user: ${CUID}:${CGID}
    volumes:
      - ${PUPY}:/opt/pupy
      - ${WORKDIR}:/project
    ports:
      - 8443:8443
      - 9000:9000
    container_name: pupy
    stdin_open: true
    tty: true
